#!/bin/bash
OPTIONS=":w:d:hastn"
WRAPCHAR=""
SEPCHAR=","
OUTPUT=""
STARTCHAR="("
ENDCHAR=")"

function help {
    echo -e "Usage:\n"
    echo -e "$0 -astnh -w wrap_character -d delimiter"
    echo
    echo -e "Output modes"
    echo -e " Flag  Mode           Example"
    echo -e "  -a   array           [1,2,3,4]"
    echo -e "  -n   none            1,2,3,4"
    echo -e "  -s   set             {1,2,3,4}"
    echo -e "  -t   tuple           (1,2,3,4)"
    echo ""
    echo "The 'wrap_character' specifies the character to use before and after each element of the output."
    echo "The 'delimiter' specifies the character to use between each element of the output."

    exit 1
}

while getopts $OPTIONS opt; do
    case $opt in
      a)
    STARTCHAR='['
    ENDCHAR=']'
    ;;
      h)
    help
    ;;
      n)
    STARTCHAR=""
    ENDCHAR=""
    ;;
      s)
    STARTCHAR='{'
    ENDCHAR='}'
    ;;
      t)
    STARTCHAR='('
    ENDCHAR=')'
    ;;
      w)
    WRAPCHAR=$OPTARG
    ;;
      d)
    SEPCHAR=$OPTARG
    ;;
     \?)
    help
    ;;
    esac
done

OUTPUT=$OUTPUT`echo -n "$STARTCHAR"`
while read line
do
   OUTPUT=$OUTPUT`echo -n "$WRAPCHAR$line$WRAPCHAR$SEPCHAR"`
done

TEMPOUT=`echo $OUTPUT | sed -e "s/$SEPCHAR$//"`
OUTPUT=$TEMPOUT`echo -n "$ENDCHAR"`
echo $OUTPUT
